spring:
  datasource:
    url: jdbc:h2:mem:nkdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      hbm2ddl.auto: update
      format_sql: true
    showSql: true
    generate-ddl: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${env.kakao.client-id}
            client-secret: ${env.kakao.client-secret}
            scope:
              - profile_nickname
              - account_email
              - gender
            redirect-uri: "{baseUrl}/{action}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: kakao
          naver:
            client-id: ${env.naver.client-id}
            client-secret: ${env.naver.client-secret}
            scope:
              - name
              - email
              - profile_image
            redirect-uri: "{baseUrl}/{action}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code # authorization_code : 발급, refresh_token : 갱신, delete : 삭제
            client-authentication-method: POST
            client-name: naver
          google:
            client-id: ${env.google.client-id}
            client-secret: ${env.google.client-secret}
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/{action}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: google

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize # 네이버 로그인 인증 요청
            token_uri: https://nid.naver.com/oauth2.0/token # 토큰 발급, 갱신, 삭제 요청
            user-info-uri: https://openapi.naver.com/v1/nid/me # 네이버 회원의 프로필 조회
            user_name_attribute: response

app:
  name: spring_oauth2

jwt:
  cookie_name: oauth_test
  expires_in: 30 # 30 day
  secret: test1234